In [49]:
#TA = int(input('Ingrese la tempratura A: '))
#TB = int(input('Ingrese la temperatura B: '))
#k = int(input('Ingrese el valor de k: '))
N = int(input('Ingrese el numero de nodos: '))
#longitu = int(input('Ingrese la longitud de su vara: '))

Ingrese el numero de nodos: 10


In [50]:
import numpy as np
h = N + 1

r = k / (h**2)

A = []
f0 = [-2, 1]

ceros0 = list(map(int, list('0'* (N-2))))
l0 = f0 + ceros0
A.append(l0)

cerosm = range(0, N-2)
f1 = [1, -2, 1]

izquierda = []
for i in cerosm:
  izquierda.append(list(map(int, list('0'*i))))
derecha = []
for i in cerosm[::-1]:
  derecha.append(list(map(int, list('0'*i))))

for i in range(len(izquierda)):
  A.append(izquierda[i] + f1 + derecha[i])

linver = l0[::-1]
A.append(linver)

#list(map(int,A))

print(np.matrix(A))


[[-2  1  0  0  0  0  0  0  0  0]
 [ 1 -2  1  0  0  0  0  0  0  0]
 [ 0  1 -2  1  0  0  0  0  0  0]
 [ 0  0  1 -2  1  0  0  0  0  0]
 [ 0  0  0  1 -2  1  0  0  0  0]
 [ 0  0  0  0  1 -2  1  0  0  0]
 [ 0  0  0  0  0  1 -2  1  0  0]
 [ 0  0  0  0  0  0  1 -2  1  0]
 [ 0  0  0  0  0  0  0  1 -2  1]
 [ 0  0  0  0  0  0  0  0  1 -2]]
